# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nullWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_nullValueWin(object):
    def setupUi(self, nullValueWin):
        nullValueWin.setObjectName("nullValueWin")
        nullValueWin.setWindowModality(QtCore.Qt.ApplicationModal)
        nullValueWin.resize(299, 212)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(nullValueWin.sizePolicy().hasHeightForWidth())
        nullValueWin.setSizePolicy(sizePolicy)
        nullValueWin.setMinimumSize(QtCore.QSize(299, 212))
        nullValueWin.setMaximumSize(QtCore.QSize(299, 212))
        self.centralwidget = QtWidgets.QWidget(nullValueWin)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblNullValues = QtWidgets.QLabel(self.centralwidget)
        self.lblNullValues.setObjectName("lblNullValues")
        self.verticalLayout.addWidget(self.lblNullValues)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.radioEmpty = QtWidgets.QRadioButton(self.centralwidget)
        self.radioEmpty.setChecked(True)
        self.radioEmpty.setObjectName("radioEmpty")
        self.verticalLayout.addWidget(self.radioEmpty)
        self.radioZero = QtWidgets.QRadioButton(self.centralwidget)
        self.radioZero.setObjectName("radioZero")
        self.verticalLayout.addWidget(self.radioZero)
        self.radioNull = QtWidgets.QRadioButton(self.centralwidget)
        self.radioNull.setObjectName("radioNull")
        self.verticalLayout.addWidget(self.radioNull)
        self.radioCustom = QtWidgets.QRadioButton(self.centralwidget)
        self.radioCustom.setObjectName("radioCustom")
        self.verticalLayout.addWidget(self.radioCustom)
        self.txtCustom = QtWidgets.QLineEdit(self.centralwidget)
        self.txtCustom.setEnabled(False)
        self.txtCustom.setObjectName("txtCustom")
        self.verticalLayout.addWidget(self.txtCustom)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOkay = QtWidgets.QPushButton(self.centralwidget)
        self.btnOkay.setObjectName("btnOkay")
        self.horizontalLayout.addWidget(self.btnOkay)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        nullValueWin.setCentralWidget(self.centralwidget)

        self.retranslateUi(nullValueWin)
        QtCore.QMetaObject.connectSlotsByName(nullValueWin)

    def retranslateUi(self, nullValueWin):
        _translate = QtCore.QCoreApplication.translate
        nullValueWin.setWindowTitle(_translate("nullValueWin", "Replace Null Values"))
        self.lblNullValues.setText(_translate("nullValueWin", "Replace Null Values with:"))
        self.radioEmpty.setText(_translate("nullValueWin", "Empty"))
        self.radioZero.setText(_translate("nullValueWin", "0 (Zero)"))
        self.radioNull.setText(_translate("nullValueWin", "Null"))
        self.radioCustom.setText(_translate("nullValueWin", "Custom"))
        self.btnOkay.setText(_translate("nullValueWin", "Okay"))
        self.btnCancel.setText(_translate("nullValueWin", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    nullValueWin = QtWidgets.QMainWindow()
    ui = Ui_nullValueWin()
    ui.setupUi(nullValueWin)
    nullValueWin.show()
    sys.exit(app.exec_())
