# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pageSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_pageWindow(object):
    def setupUi(self, pageWindow):
        pageWindow.setObjectName("pageWindow")
        pageWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        pageWindow.resize(501, 602)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(pageWindow.sizePolicy().hasHeightForWidth())
        pageWindow.setSizePolicy(sizePolicy)
        pageWindow.setMinimumSize(QtCore.QSize(501, 602))
        pageWindow.setMaximumSize(QtCore.QSize(501, 602))
        self.centralwidget = QtWidgets.QWidget(pageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tblPage = QtWidgets.QTableWidget(self.centralwidget)
        self.tblPage.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tblPage.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.tblPage.setObjectName("tblPage")
        self.tblPage.setColumnCount(0)
        self.tblPage.setRowCount(0)
        self.verticalLayout.addWidget(self.tblPage)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        self.btnBack.setObjectName("btnBack")
        self.horizontalLayout.addWidget(self.btnBack)
        self.lblPageNum = QtWidgets.QLabel(self.centralwidget)
        self.lblPageNum.setAlignment(QtCore.Qt.AlignCenter)
        self.lblPageNum.setObjectName("lblPageNum")
        self.horizontalLayout.addWidget(self.lblPageNum)
        self.btnForward = QtWidgets.QPushButton(self.centralwidget)
        self.btnForward.setObjectName("btnForward")
        self.horizontalLayout.addWidget(self.btnForward)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.btnOpen.setObjectName("btnOpen")
        self.horizontalLayout_2.addWidget(self.btnOpen)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        pageWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(pageWindow)
        QtCore.QMetaObject.connectSlotsByName(pageWindow)

    def retranslateUi(self, pageWindow):
        _translate = QtCore.QCoreApplication.translate
        pageWindow.setWindowTitle(_translate("pageWindow", "Select Page"))
        self.btnBack.setText(_translate("pageWindow", "<"))
        self.lblPageNum.setText(_translate("pageWindow", "Page 1"))
        self.btnForward.setText(_translate("pageWindow", ">"))
        self.btnOpen.setText(_translate("pageWindow", "Open Page"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    pageWindow = QtWidgets.QMainWindow()
    ui = Ui_pageWindow()
    ui.setupUi(pageWindow)
    pageWindow.show()
    sys.exit(app.exec_())
