# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'renameColWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_renameColumnWindow(object):
    def setupUi(self, renameColumnWindow):
        renameColumnWindow.setObjectName("renameColumnWindow")
        renameColumnWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        renameColumnWindow.resize(288, 99)
        self.centralwidget = QtWidgets.QWidget(renameColumnWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblRename = QtWidgets.QLabel(self.centralwidget)
        self.lblRename.setObjectName("lblRename")
        self.verticalLayout.addWidget(self.lblRename)
        self.txtRename = QtWidgets.QLineEdit(self.centralwidget)
        self.txtRename.setObjectName("txtRename")
        self.verticalLayout.addWidget(self.txtRename)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOkay = QtWidgets.QPushButton(self.centralwidget)
        self.btnOkay.setObjectName("btnOkay")
        self.horizontalLayout.addWidget(self.btnOkay)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        renameColumnWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(renameColumnWindow)
        QtCore.QMetaObject.connectSlotsByName(renameColumnWindow)

    def retranslateUi(self, renameColumnWindow):
        _translate = QtCore.QCoreApplication.translate
        renameColumnWindow.setWindowTitle(_translate("renameColumnWindow", "Rename Column"))
        self.lblRename.setText(_translate("renameColumnWindow", "Rename Column:"))
        self.btnOkay.setText(_translate("renameColumnWindow", "Okay"))
        self.btnCancel.setText(_translate("renameColumnWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    renameColumnWindow = QtWidgets.QMainWindow()
    ui = Ui_renameColumnWindow()
    ui.setupUi(renameColumnWindow)
    renameColumnWindow.show()
    sys.exit(app.exec_())
