# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'trimWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_trimWindow(object):
    def setupUi(self, trimWindow):
        trimWindow.setObjectName("trimWindow")
        trimWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        trimWindow.resize(365, 184)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(trimWindow.sizePolicy().hasHeightForWidth())
        trimWindow.setSizePolicy(sizePolicy)
        trimWindow.setMinimumSize(QtCore.QSize(365, 184))
        trimWindow.setMaximumSize(QtCore.QSize(365, 184))
        self.centralwidget = QtWidgets.QWidget(trimWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setTextFormat(QtCore.Qt.RichText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.horizontalSlider = QtWidgets.QSlider(self.centralwidget)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_2.addWidget(self.horizontalSlider)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioLeft = QtWidgets.QRadioButton(self.centralwidget)
        self.radioLeft.setChecked(True)
        self.radioLeft.setObjectName("radioLeft")
        self.horizontalLayout_3.addWidget(self.radioLeft)
        self.radioRight = QtWidgets.QRadioButton(self.centralwidget)
        self.radioRight.setObjectName("radioRight")
        self.horizontalLayout_3.addWidget(self.radioRight)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnOkay = QtWidgets.QPushButton(self.centralwidget)
        self.btnOkay.setObjectName("btnOkay")
        self.horizontalLayout_4.addWidget(self.btnOkay)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        trimWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(trimWindow)
        QtCore.QMetaObject.connectSlotsByName(trimWindow)

    def retranslateUi(self, trimWindow):
        _translate = QtCore.QCoreApplication.translate
        trimWindow.setWindowTitle(_translate("trimWindow", "Trim data"))
        self.label.setText(_translate("trimWindow", "Text"))
        self.radioLeft.setText(_translate("trimWindow", "Trim Left"))
        self.radioRight.setText(_translate("trimWindow", "Trim Right"))
        self.btnOkay.setText(_translate("trimWindow", "Okay"))
        self.btnCancel.setText(_translate("trimWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    trimWindow = QtWidgets.QMainWindow()
    ui = Ui_trimWindow()
    ui.setupUi(trimWindow)
    trimWindow.show()
    sys.exit(app.exec_())
