# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'typeWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_typeWindow(object):
    def setupUi(self, typeWindow):
        typeWindow.setObjectName("typeWindow")
        typeWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        typeWindow.resize(226, 175)
        typeWindow.setMinimumSize(QtCore.QSize(226, 175))
        typeWindow.setMaximumSize(QtCore.QSize(226, 175))
        self.centralwidget = QtWidgets.QWidget(typeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lblType = QtWidgets.QLabel(self.centralwidget)
        self.lblType.setObjectName("lblType")
        self.verticalLayout.addWidget(self.lblType)
        self.radioInt = QtWidgets.QRadioButton(self.centralwidget)
        self.radioInt.setObjectName("radioInt")
        self.verticalLayout.addWidget(self.radioInt)
        self.radioFloat = QtWidgets.QRadioButton(self.centralwidget)
        self.radioFloat.setObjectName("radioFloat")
        self.verticalLayout.addWidget(self.radioFloat)
        self.radioString = QtWidgets.QRadioButton(self.centralwidget)
        self.radioString.setObjectName("radioString")
        self.verticalLayout.addWidget(self.radioString)
        self.radioObject = QtWidgets.QRadioButton(self.centralwidget)
        self.radioObject.setObjectName("radioObject")
        self.verticalLayout.addWidget(self.radioObject)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnOkay = QtWidgets.QPushButton(self.centralwidget)
        self.btnOkay.setObjectName("btnOkay")
        self.horizontalLayout.addWidget(self.btnOkay)
        self.btnCancel = QtWidgets.QPushButton(self.centralwidget)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        typeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(typeWindow)
        QtCore.QMetaObject.connectSlotsByName(typeWindow)

    def retranslateUi(self, typeWindow):
        _translate = QtCore.QCoreApplication.translate
        typeWindow.setWindowTitle(_translate("typeWindow", "Change Data Type"))
        self.lblType.setText(_translate("typeWindow", "Change Data Type:"))
        self.radioInt.setText(_translate("typeWindow", "Integer"))
        self.radioFloat.setText(_translate("typeWindow", "Float"))
        self.radioString.setText(_translate("typeWindow", "String"))
        self.radioObject.setText(_translate("typeWindow", "Object"))
        self.btnOkay.setText(_translate("typeWindow", "Okay"))
        self.btnCancel.setText(_translate("typeWindow", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    typeWindow = QtWidgets.QMainWindow()
    ui = Ui_typeWindow()
    ui.setupUi(typeWindow)
    typeWindow.show()
    sys.exit(app.exec_())
